### ISSUE TITLE
huggingface load failed

### ISSUE THREAD

**Issue by wddddi** [DoubleClass/GMM#12]
OSError: Can't load tokenizer for 'C:\Users\Administrator\.cache\huggingface\hub\'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'C:\Users\Administrator\.cache\huggingface\hub\' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer.

**Comment by wddddi** [comment]
OSError: Can't load tokenizer for 'C:/Users/Administrator/.cache/huggingface/hub/models--bert-base-uncased'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'C:/Users/Administrator/.cache/huggingface/hub/models--bert-base-uncased' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer.

**Comment by DoubleClass** [comment]
Thank you for your interest in our work! Make sure you have already downloaded the bert model from the BaiduNetDisk and put it in the corresponding dir. If that doesn't work. You can try delete this dir and run the training code, it will automatically download from huggingface.

**Comment by wddddi** [comment]
您好，您的邮件已收到。谢谢
