### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by wddddi** [DoubleClass/GMM#13]
I want to conduct an evaluation using my own dataset, what code do I need to change, and what format should my dataset be in?

**Comment by wddddi** [comment]
I want to perform class-incremental image classification. My dataset contains 11 classes, formatted as mydata_image/test/red_bird, mydata_image/test/green_bird, mydata_image/test/yellow_bird, and so on. what code do I need to change?

**Comment by DoubleClass** [comment]
You need to customize your dataset like the imgr example provided in this repo and put the corresponding directory in the GMM/minigpt4/configs/datasets/cc_sbu/align.yaml file. Then create and change the task split file in 'GMM/minigpt4/datasets/builders/image_text_pair_builder.py'
