### ISSUE TITLE
Ask about FSCIL

### ISSUE THREAD

**Issue by trinh-hoang-hiep** [DoubleClass/GMM#7]
First I would like to thank you very much for your great work. I'm interested in the FSCIL problem in your work. Can you give me instructions for running Cifar and ImageNet100 5-way 5-shot settings? I want to reproduce the results of table 2 and table 3.
Thank you very much.

**Comment by DoubleClass** [comment]
The training protocol of the FSCIL is exactly the same with the CIL settings except the data files, here is the example of the Tiny ImageNet data files:  https://pan.baidu.com/s/1q8TfOCotojp2kWOrBJuJLg?pwd=nuyr  code: nuyr 
Hope this will help you
