### ISSUE TITLE
Questions about the loss of training

### ISSUE THREAD

**Issue by 1125178969** [DoubleClass/GMM#9]
Hello, that's a great job, can you release your training log or can you say something about the drop in losses you trained for?

**Comment by DoubleClass** [comment]
I apologize for the delay in my response. Could you please elaborate on your question in more detail?
Could you provide your email so I can send you the training logs?

**Comment by 1125178969** [comment]
I'd like to apply MiniGPT4 to multi-label classification, but I'm not sure roughly how much convergence of the final Loss is appropriate, so I'd like to refer to your training log. My email is jdjinahu@foxmail.com
